### ISSUE TITLE
Complemento aparece en el objeto principal

### ISSUE THREAD

**Issue by jacobmeneses** [onefacture/cfdi-to-json#4]
Algunos elementos del complemento aparecen el el objeto principal y no en su llave como el emisor o receptor
```
{
...,
  uuid: '',
  noCertificadoSAT: '',
  selloSAT:'',
  selloCFD:'' 
}
```

**Comment by ricaralan** [comment]
Que tal @jacobmeneses,

Aún no subimos documentación sobre la librería (Lo haremos dentro de poco). Pero el funcionamiento esta pensado de esta forma.

    {
        "emisor": { ... },
        "receptor": { ... },
        "impuestos": { ... },
        "pagos":   ...cfdi.complementos.pagos,
        "nomina":  ...cfdi.complementos.nomina,
        [NOMBRE_NOTACION_CAMEL_CASE]: ...cfdi.complementos[COMPLEMENTO]
        ...cfdi.complementos.timbre
    }

Te recomendamos que verifiques que los nodos salen correctamente debido a que acabamos de añadir los test de funcionalidad básica de nuestros modelos JSON. Pero aún estamos haciendo los test de los complementos menos comunes.

Nos puedes preguntar por si tienes alguna duda y subimos la mejora o en todo caso si te das cuenta que le falta algún dato puedes hacer un pull-request para solucionarlo.


Saludos!
